name: Auto Promote to Main-Promotion

on:
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  promote:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Fetch and reset main-promotion
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin main-promotion:main-promotion
        git checkout -b main-promotion
        git reset --hard dev

    - name: Push to new branch
      run: |
        git push origin main-promotion --force

    - name: Create PR to main
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main-promotion
        base: main
        title: '[AUTO-PR] Promote from dev to main-promotion'
        body: 'Automated PR from dev merge. Please review.'
        commit-message: 'chore: promote dev to main-promotion'
